<style type="text/css">
<!--
.STYLE1 {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 14px;
	line-height: 18px;
}
.STYLE2 {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 14px;
	font-weight: bold;
	line-height: 20px;
}
-->
</style>
<p class="STYLE2">&nbsp;</p>
<p class="STYLE1">We values the users of our website (the &quot;Website&quot;). Your privacy and trust are very important to us. We recognize that you may be concerned about our collection, use, and disclosure of the personally identifiable information (&quot;Personal Information&quot;) that we collect when you use the Website and the services offered on the Website. This Privacy Policy describes the information that we collect from you, how we collect this information, and what we do with it after we collect it. By using the Website you are accepting the practices described in this Privacy Policy. If you have any questions or comments regarding this Privacy Policy, please contact us at service@customdolls.com.au.</p>
<p class="STYLE2">Do we Ever Make Changes to its Privacy Policy? </p>
<p class="STYLE1">We may make changes to the Privacy Policy from time to time. We will notify you of any changes by sending you an email, posting a notice on the home page of the Website, or posting a notice in your account when you first login after we have made changes. If you receive notification of a change in our Privacy Policy, you must review the new Privacy Policy carefully to make sure you understand our practices and procedures. You may not be able to receive notices from us if your cookies are not set to accept and/or are disabled. </p>
<p class="STYLE2">What Types of Information Collect From Me? </p>
<p class="STYLE1">Personal Information. We collect Personal Information that you provide to us, such as your name, mailing address, phone number, email address, credit card number, and financial information. We will also collect photos related to the product order that you are placing, and potentially logos, other images and a description of your order. <br />
  Non-Personal Information. We also collect non-personal information from you, such as your browser type, the URL of the previous website you visited, your ISP, operating system, and your Internet protocol (IP) Address (&quot;Non-Personal Information&quot;). Non-Personal Information cannot be easily used to personally identify you. </p>
<p class="STYLE2">How and When do we Collect This Information? </p>
<p class="STYLE1">Providing Information to Us. We collect Personal Information from you when you provide it to us. For example, if you purchase a product sold through a Shop, we may collect your name, mailing address, telephone number, credit card number, and email address. If you create a Shopkeeper or Affiliate Account, we may collect your name, tax identification number, mailing address, email address, and other information that we request during the registration process, and any information that you provide to our affiliates. If you sign up to receive a newsletter, we will collect your email address. </p>
<p class="STYLE1">Analytic and Reporting Technologies. Like the operators of most websites, we use analytic and reporting technologies to record Non-Personal Information such as Internet domain and host names, Internet protocol (IP) addresses, browser software, operating system types, clickstream patterns, and the dates and times that the Website and the products and services are accessed. We also contract with several online partners to help manage, monitor and optimize our Website and the products and services and to help us measure the effectiveness of our advertising, communications and how visitors use the Website. To do this, we may use web beacons and cookies. </p>
<p class="STYLE2">How do we use personal Information? </p>
<p class="STYLE1">Personal Information. We use Personal Information primarily for our own internal purposes, such as providing, maintaining, evaluating, and improving the products, services, and the Website, fulfilling requests for information, producing and shipping the products that you order, and providing customer support. For example, if you sign up to receive a newsletter, we will use the email address you provide to send you the newsletters. <br />
  We will not use your photos, written communications or any other information from your order on our website or in other marketing materials, without your permission, generally given through an email approval. Such permission may be revoked and we will remove the previously approved content from our website within 10 working days. However, any pre-printed materials including the content will continue to be used until the existing supply is exhausted. <br />
  Non-Personal Information. We use Non-Personal Information to track the use of the Website and products and servcies and for other internal purposes, such as providing, maintaining, evaluating, and improving the products and services and the Website. </p>
<p class="STYLE2">When Will Disclose Your Information to Third Parties? </p>
<p class="STYLE1">Disclosure to Successors. We may disclose your Personal Information to any successor-in-interest of ours, such as a company that acquires us. In the event we goes through a business transition, such as a merger or acquisition by or with another company, or sale of all or a portion of our assets, your Personal Information will likely be among the assets transferred. You will be notified via email or by a notice on our Website of any such change in ownership or control of your Personal Information. <br />
  Disclosure to Unaffiliated Third Parties. We may disclose your Personal Information to prevent an emergency, to prevent harm to others, to respond to legal requirements, to protect or enforce our rights and policies, to protect or enforce the rights of a third party, or as required or permitted by law (including, without limitation, to comply with a subpoena or court order). </p>
<p class="STYLE1">Disclosure to Third Party Service Providers and Online Partners. We may contract with various third parties who help us provide, maintain and improve the Website and the products and services. For example, we use a third party to process payments made to us, and may subcontract production, fulfillment, analytics, reporting or other operations. We also contract with several online partners to help manage, monitor and optimize our Website and the products and services and to help us measure the effectiveness of our advertising, communications and how visitors use the Website. We will use commercially reasonable efforts to prevent such third parties from disclosing your Personal Information, except for the purpose of providing the services in question. We cannot guarantee that such third parties will not disclose your Personal Information. </p>
<p class="STYLE1">Disclosure of Non-Personal Information. We will disclose Non-Personal Information, in aggregate form, to potential strategic partners, advertisers, investors, customers, and others. You may not opt-out of the sharing of this information. However, it cannot be easily used to identify you personally. </p>
<p class="STYLE2">What About Cookies and Web Beacons? </p>
<p class="STYLE1">A cookie is a small file placed on the hard drive of your computer. Most websites use cookies. We use cookies to track your use of the Website and the products and services, to provide you with a more personalized user experience, and to allow you to login and begin use products and services automatically when you visit the Website. <br />
  A web beacon is an often-transparent graphic image, usually no larger than a 1x1 pixel that is placed on a web page or in an e-mail that is used to monitor the behavior of the user visiting the Website or receiving the e-mail. </p>
<p class="STYLE2">Do we protect your Personal Information? </p>
<p class="STYLE1">Personal Information. Whenever we obtain your Personal Information, we use commercially reasonable efforts to protect it from unauthorized access or disclosure. However, we are not insurers of the security of your Personal Information. Accordingly, we assume no liability for any disclosure of data due to errors in transmission, unauthorized third party access or other acts of third parties, or acts or omissions beyond our reasonable control. </p>
<p class="STYLE2">How Can I Review and Make Changes to My Personal Information? </p>
<p class="STYLE1">You can obtain a copy of and request that we correct errors in your Personal Information by emailing us at service@customdolls.com.au. For your protection, you will be required to provide proof of your identity to obtain a copy of your Personal Information. If your Personal Information changes or if you no longer want to use the products and services, you may correct, update or deactivate your Personal Information and/or your account through the account management screen. If you would like to deactivate or terminate your account you can also contact us at service@customdolls.com.au. <br />
</p>
<p class="STYLE2">Tell-A-Friend </p>
<p class="STYLE1">If you choose to use our referral service to tell a friend about the Website or our products and services, we will ask you for your friend's name and email address. We will automatically send your friend a one-time email inviting him or her to visit the Website. We store this information for the sole purpose of sending this one-time email and tracking the success of our referral program. </p>
<p class="STYLE2">Security </p>
<p class="STYLE1">The security of your Personal Information is important to us. When you enter sensitive information such as a credit card number and/or social security number on our registration or order forms, we encrypt that information using secure socket layer technology (SSL). <br />
  We follow generally accepted industry standards to protect the Personal Information submitted to us, both during transmission and once we receive it. However, no method of transmission over the Internet, or method of electronic storage, is 100% secure. Therefore, while we strive to use commercially acceptable means to protect your Personal Information, we cannot guarantee its absolute security. </p>
<p class="STYLE2">Does This Privacy Policy Apply When I Access Third Party Websites? </p>
<p class="STYLE1">You may be able to access third party websites directly from the Website. This Privacy Policy does not apply when you access third party websites. We cannot control how third parties may use Personal Information you disclose to them, so you should carefully review the privacy policy of any third party website you visit before using it or disclosing your Personal Information to its provider. </p>
<p class="STYLE2">Can I Opt-Out From Receiving Communications From us? </p>
<p class="STYLE1">We provide you the opportunity to opt-out of having your Personal Information used for certain purposes. For example, if you purchase a product/service but do not wish to receive any additional marketing material from us, you can indicate your preference on our order form. </p>
<p class="STYLE2">How are images of my doll used? </p>
<p class="STYLE1">We reserves the right to send images of the custom bobblehead dolls or other products to the email address provided by the customer at the time of ordering. These images may be superimposed on various background scenes, included in video games or included in video productions. Any forwarding or sending of these images to others beyond the party ordering the product - whether authorized or unauthorized, in electronic or physical form is not the responsibility of ours. <br />
</p>
